"""Initial schema

Revision ID: 42ce285a2f17
Revises: 
Create Date: 2026-02-27 13:52:36.286572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ce285a2f17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_tasks',
    sa.Column('id', sa.UUID(), nullable=False, comment='Первинний ключ — повертається клієнту одразу після POST /optimize'),
    sa.Column('target_date', sa.Date(), nullable=False, comment='Дата, для якої будується розклад'),
    sa.Column('technician_ids', sa.String(length=4000), nullable=True, comment='JSON-масив UUID техніків. NULL = всі активні техніки'),
    sa.Column('service_site_ids', sa.String(length=4000), nullable=True, comment="JSON-масив UUID об'єктів. NULL = всі pending-заявки"),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False, comment='Ліміт часу для OR-Tools solver (сек)'),
    sa.Column('first_solution_strategy', sa.String(length=100), nullable=False, comment='Стратегія першого рішення. Напр: PATH_CHEAPEST_ARC, PARALLEL_CHEAPEST_INSERTION'),
    sa.Column('local_search_metaheuristic', sa.String(length=100), nullable=False, comment='Метаевристика локального пошуку. Напр: GUIDED_LOCAL_SEARCH, SIMULATED_ANNEALING'),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'SUCCESS', 'FAILED', 'RETRYING', name='task_status_enum'), nullable=False, comment='Поточний стан задачі в черзі Dramatiq'),
    sa.Column('dramatiq_message_id', sa.String(length=255), nullable=True, comment='ID повідомлення в RabbitMQ — для трасування та відлагодження'),
    sa.Column('routes_created', sa.Integer(), nullable=True, comment='Скільки маршрутів побудовано'),
    sa.Column('sites_unassigned', sa.Integer(), nullable=True, comment="Скільки об'єктів не вдалось включити"),
    sa.Column('total_distance_km', sa.Numeric(precision=10, scale=2), nullable=True, comment='Загальний пробіг по всіх маршрутах (км)'),
    sa.Column('error_message', sa.String(length=2000), nullable=True, comment='Повідомлення про помилку або traceback (при FAILED)'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Кількість повторних спроб — Dramatiq збільшує при кожному retry'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Час створення (POST /optimize)'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='Коли воркер взяв задачу'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Час завершення (успіх або провал)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opt_tasks_message_id', 'optimization_tasks', ['dramatiq_message_id'], unique=False)
    op.create_index('ix_opt_tasks_status', 'optimization_tasks', ['status'], unique=False)
    op.create_index('ix_opt_tasks_target_date', 'optimization_tasks', ['target_date'], unique=False)
    op.create_table('technicians',
    sa.Column('id', sa.UUID(), nullable=False, comment='Первинний ключ — UUID v4, генерується на рівні Python'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Повне ім'я техніка. З Excel: «Name»"),
    sa.Column('home_address', sa.String(length=500), nullable=True, comment='З Excel: «Home address»'),
    sa.Column('home_latitude', sa.Numeric(precision=10, scale=8), nullable=True, comment='Широта (-90..90)'),
    sa.Column('home_longitude', sa.Numeric(precision=11, scale=8), nullable=True, comment='Довгота (-180..180)'),
    sa.Column('office_address', sa.String(length=500), nullable=True, comment='З Excel: «Office address»'),
    sa.Column('office_latitude', sa.Numeric(precision=10, scale=8), nullable=True, comment='Широта офісу'),
    sa.Column('office_longitude', sa.Numeric(precision=11, scale=8), nullable=True, comment='Довгота офісу'),
    sa.Column('starts_from', sa.Enum('HOME', 'OFFICE', 'EITHER_WORKS', name='start_point_enum'), nullable=False, comment='Звідки технік починає день. З Excel: «Starts from»'),
    sa.Column('finishes_at', sa.Enum('HOME', 'OFFICE', 'EITHER_WORKS', name='start_point_enum'), nullable=False, comment='Де технік закінчує день. З Excel: «Finishes at»'),
    sa.Column('transport_mode', sa.Enum('CAR_VAN', 'WALK', 'DRIVE_TO_HUB_AND_WALK', name='transport_mode_enum'), nullable=False, comment='Вид транспорту. Для оптимізації розраховується лише car_van'),
    sa.Column('monday_start', sa.Time(), nullable=True, comment='Понеділок — початок'),
    sa.Column('monday_end', sa.Time(), nullable=True, comment='Понеділок — кінець'),
    sa.Column('tuesday_start', sa.Time(), nullable=True, comment='Вівторок — початок'),
    sa.Column('tuesday_end', sa.Time(), nullable=True, comment='Вівторок — кінець'),
    sa.Column('wednesday_start', sa.Time(), nullable=True, comment='Середа — початок'),
    sa.Column('wednesday_end', sa.Time(), nullable=True, comment='Середа — кінець'),
    sa.Column('thursday_start', sa.Time(), nullable=True, comment='Четвер — початок'),
    sa.Column('thursday_end', sa.Time(), nullable=True, comment='Четвер — кінець'),
    sa.Column('friday_start', sa.Time(), nullable=True, comment="П'ятниця — початок"),
    sa.Column('friday_end', sa.Time(), nullable=True, comment="П'ятниця — кінець"),
    sa.Column('saturday_start', sa.Time(), nullable=True, comment='Субота — початок (часто NULL)'),
    sa.Column('saturday_end', sa.Time(), nullable=True, comment='Субота — кінець'),
    sa.Column('sunday_start', sa.Time(), nullable=True, comment='Неділя — початок (зазвичай NULL)'),
    sa.Column('sunday_end', sa.Time(), nullable=True, comment='Неділя — кінець'),
    sa.Column('max_hours_per_day', sa.Integer(), nullable=False, comment='Максимум годин за день. З Excel: «Maximum hours of work per day for service»'),
    sa.Column('max_hours_per_week', sa.Integer(), nullable=False, comment='Максимум годин за тиждень. З Excel: «Maximum hours of work per week for service»'),
    sa.Column('break_duration_minutes', sa.Integer(), nullable=True, comment='З Excel: «Min break per day, minutes»'),
    sa.Column('break_earliest_start', sa.Time(), nullable=True, comment='З Excel: «Break not earlier than»'),
    sa.Column('break_latest_start', sa.Time(), nullable=True, comment='З Excel: «Break not later than»'),
    sa.Column('can_do_physically_demanding', sa.Boolean(), nullable=False, comment='З Excel: «Can do physically demanding job»'),
    sa.Column('skilled_in_living_walls', sa.Boolean(), nullable=False, comment='З Excel: «Skilled in living walls»'),
    sa.Column('comfortable_with_heights', sa.Boolean(), nullable=False, comment='З Excel: «Comfortable with work at heights»'),
    sa.Column('certified_with_lift', sa.Boolean(), nullable=False, comment='З Excel: «Certified with using the lift»'),
    sa.Column('has_pesticide_certification', sa.Boolean(), nullable=False, comment='З Excel: «Pesticide applicator certification»'),
    sa.Column('is_citizen', sa.Boolean(), nullable=False, comment='З Excel: «Is a citizen»'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False = звільнений або тимчасово недоступний'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('home_latitude  IS NULL OR home_latitude  BETWEEN -90  AND 90', name='ck_technicians_home_lat'),
    sa.CheckConstraint('home_longitude IS NULL OR home_longitude BETWEEN -180 AND 180', name='ck_technicians_home_lon'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_technicians_home_coords', 'technicians', ['home_latitude', 'home_longitude'], unique=False)
    op.create_index('ix_technicians_is_active', 'technicians', ['is_active'], unique=False)
    op.create_index('ix_technicians_name', 'technicians', ['name'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('technician_id', sa.UUID(), nullable=False, comment='FK на техніка — маршрут завжди належить конкретному спеціалісту'),
    sa.Column('route_date', sa.Date(), nullable=False, comment='Дата виконання маршруту'),
    sa.Column('status', sa.Enum('DRAFT', 'OPTIMIZED', 'IN_PROGRESS', 'COMPLETED', name='route_status_enum'), nullable=False, comment='Поточний стан у lifecycle'),
    sa.Column('total_distance_km', sa.Numeric(precision=10, scale=2), nullable=True, comment='Загальний пробіг за день (км)'),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=True, comment='Тривалість від першої до останньої зупинки (хв)'),
    sa.Column('total_travel_time_minutes', sa.Integer(), nullable=True, comment='Чистий час у дорозі між зупинками (хв)'),
    sa.Column('stops_count', sa.Integer(), nullable=False, comment="Кількість об'єктів у маршруті"),
    sa.Column('optimization_time_seconds', sa.Numeric(precision=10, scale=3), nullable=True, comment='Час роботи OR-Tools solver (сек)'),
    sa.Column('optimization_objective_value', sa.Numeric(precision=15, scale=2), nullable=True, comment='Значення цільової функції OR-Tools (менше — краще)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('optimized_at', sa.DateTime(timezone=True), nullable=True, comment='Коли OR-Tools завершив оптимізацію'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='Коли технік виїхав'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Коли завершив усі зупинки'),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technician_id', 'route_date', name='uq_route_technician_date')
    )
    op.create_index('ix_routes_date', 'routes', ['route_date'], unique=False)
    op.create_index('ix_routes_status', 'routes', ['status'], unique=False)
    op.create_index('ix_routes_technician_date', 'routes', ['technician_id', 'route_date'], unique=False)
    op.create_table('service_sites',
    sa.Column('id', sa.UUID(), nullable=False, comment='Первинний ключ — UUID v4'),
    sa.Column('site_code', sa.String(length=50), nullable=False, comment="Унікальний код об'єкта. З Excel: «Site name or code» (напр. KY-0001-INT)"),
    sa.Column('site_name', sa.String(length=255), nullable=True, comment="Назва об'єкта"),
    sa.Column('address', sa.String(length=500), nullable=True, comment='З Excel: «Site address»'),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True, comment='Широта (-90..90)'),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True, comment='Довгота (-180..180)'),
    sa.Column('best_accessed_by', sa.Enum('CAR_VAN', 'WALK', 'DRIVE_TO_HUB_AND_WALK', name='transport_mode_enum'), nullable=True, comment='З Excel: «Site best accessed by»'),
    sa.Column('requires_permit', sa.Boolean(), nullable=False, comment='Потрібен дозвіл служби безпеки. Якщо true — технік має бути у service_permit_holders. З Excel: «Entrance permit»'),
    sa.Column('duration_minutes', sa.Integer(), nullable=False, comment='Планова тривалість візиту (хв). З Excel: «Est duration of the visit, minutes»'),
    sa.Column('visit_frequency', sa.Enum('X1', 'X2', 'X3', 'X4', 'X5', name='visit_frequency_enum'), nullable=False, comment='Частота відвідувань. З Excel: «Visit frequency» (1x–5x a week)'),
    sa.Column('is_physically_demanding', sa.Boolean(), nullable=False, comment='З Excel: «Physically demanding job»'),
    sa.Column('has_living_walls', sa.Boolean(), nullable=False, comment='З Excel: «Has living walls»'),
    sa.Column('requires_work_at_heights', sa.Boolean(), nullable=False, comment='З Excel: «Work at heights»'),
    sa.Column('requires_lift_usage', sa.Boolean(), nullable=False, comment='З Excel: «Requires using the lift»'),
    sa.Column('requires_pesticide_application', sa.Boolean(), nullable=False, comment='З Excel: «Requires application of pesticides»'),
    sa.Column('requires_citizen_technician', sa.Boolean(), nullable=False, comment='З Excel: «Requires a citizen technician»'),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='service_status_enum'), nullable=False, comment='Стан заявки у lifecycle'),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='service_priority_enum'), nullable=False, comment='Пріоритет — вага штрафу за невиконання в OR-Tools'),
    sa.Column('current_technician_id', sa.UUID(), nullable=True, comment='Поточний закріплений технік (soft constraint). З Excel: «Current technician»'),
    sa.Column('assigned_technician_id', sa.UUID(), nullable=True, comment='Технік, призначений після оптимізації OR-Tools'),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='ck_service_sites_positive_duration'),
    sa.CheckConstraint('latitude  IS NULL OR latitude  BETWEEN -90  AND 90', name='ck_service_sites_lat'),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name='ck_service_sites_lon'),
    sa.ForeignKeyConstraint(['assigned_technician_id'], ['technicians.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_technician_id'], ['technicians.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_code')
    )
    op.create_index('ix_service_sites_coords', 'service_sites', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_service_sites_priority', 'service_sites', ['priority'], unique=False)
    op.create_index('ix_service_sites_site_code', 'service_sites', ['site_code'], unique=False)
    op.create_index('ix_service_sites_status', 'service_sites', ['status'], unique=False)
    op.create_table('technician_skills',
    sa.Column('technician_id', sa.UUID(), nullable=False, comment='FK на техніка — при видаленні техніка записи видаляються каскадно'),
    sa.Column('skill_type', sa.Enum('INTERIOR', 'EXTERIOR', 'FLORAL', name='skill_type_enum'), nullable=False, comment='Тип сервісу: interior | exterior | floral'),
    sa.Column('skill_level', sa.Enum('JUNIOR', 'MEDIOR', 'SENIOR', name='skill_level_enum'), nullable=False, comment='Рівень кваліфікації: junior | medior | senior'),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('technician_id', 'skill_type', 'skill_level'),
    comment='Навички техніка (M2M). PK = (technician_id, skill_type, skill_level)'
    )
    op.create_table('route_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False, comment='FK на маршрут. Каскадне видалення разом із маршрутом'),
    sa.Column('service_site_id', sa.UUID(), nullable=False, comment="FK на об'єкт, який відвідується на цій зупинці"),
    sa.Column('sequence_number', sa.Integer(), nullable=False, comment='Порядковий номер зупинки (від 1). CHECK: > 0'),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False, comment="Розрахунковий час прибуття на об'єкт"),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False, comment='Час відбуття = arrival_time + duration_minutes'),
    sa.Column('travel_time_from_previous_minutes', sa.Integer(), nullable=True, comment='Час у дорозі від попередньої зупинки (хв)'),
    sa.Column('distance_from_previous_km', sa.Numeric(precision=10, scale=2), nullable=True, comment='Відстань від попередньої зупинки (км), Haversine'),
    sa.CheckConstraint('arrival_time < departure_time', name='ck_route_stop_times'),
    sa.CheckConstraint('sequence_number > 0', name='ck_route_stop_positive_seq'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_site_id'], ['service_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'sequence_number', name='uq_route_stop_sequence')
    )
    op.create_index('ix_route_stops_route_id', 'route_stops', ['route_id'], unique=False)
    op.create_index('ix_route_stops_site_id', 'route_stops', ['service_site_id'], unique=False)
    op.create_table('service_forbidden_technicians',
    sa.Column('service_site_id', sa.UUID(), nullable=False),
    sa.Column('technician_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['service_site_id'], ['service_sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_site_id', 'technician_id'),
    comment="Заборонені техніки для об'єкта (M2M, hard constraint)"
    )
    op.create_table('service_permit_holders',
    sa.Column('service_site_id', sa.UUID(), nullable=False),
    sa.Column('technician_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['service_site_id'], ['service_sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_site_id', 'technician_id'),
    comment="Техніки з перепусткою на об'єкт (M2M, hard constraint). Актуально лише коли service_sites.requires_permit = true."
    )
    op.create_table('service_preferred_technicians',
    sa.Column('service_site_id', sa.UUID(), nullable=False),
    sa.Column('technician_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['service_site_id'], ['service_sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_site_id', 'technician_id'),
    comment="Бажані техніки для об'єкта (M2M, soft constraint)"
    )
    op.create_table('service_required_skills',
    sa.Column('service_site_id', sa.UUID(), nullable=False),
    sa.Column('skill_type', sa.Enum('INTERIOR', 'EXTERIOR', 'FLORAL', name='skill_type_enum'), nullable=False),
    sa.Column('skill_level', sa.Enum('JUNIOR', 'MEDIOR', 'SENIOR', name='skill_level_enum'), nullable=False),
    sa.ForeignKeyConstraint(['service_site_id'], ['service_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_site_id', 'skill_type', 'skill_level'),
    comment="Мінімальні навички для обслуговування об'єкта (M2M, hard constraint)"
    )
    op.create_table('service_time_windows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_site_id', sa.UUID(), nullable=False, comment="FK на об'єкт. Каскадне видалення разом з об'єктом"),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='day_of_week_enum'), nullable=False, comment='День тижня, у який діє це вікно'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='Початок вікна (напр. 08:00)'),
    sa.Column('end_time', sa.Time(), nullable=False, comment='Кінець вікна (напр. 16:00). CHECK: > start_time'),
    sa.CheckConstraint('start_time < end_time', name='ck_time_window_valid'),
    sa.ForeignKeyConstraint(['service_site_id'], ['service_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_time_windows_site_id', 'service_time_windows', ['service_site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_time_windows_site_id', table_name='service_time_windows')
    op.drop_table('service_time_windows')
    op.drop_table('service_required_skills')
    op.drop_table('service_preferred_technicians')
    op.drop_table('service_permit_holders')
    op.drop_table('service_forbidden_technicians')
    op.drop_index('ix_route_stops_site_id', table_name='route_stops')
    op.drop_index('ix_route_stops_route_id', table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_table('technician_skills')
    op.drop_index('ix_service_sites_status', table_name='service_sites')
    op.drop_index('ix_service_sites_site_code', table_name='service_sites')
    op.drop_index('ix_service_sites_priority', table_name='service_sites')
    op.drop_index('ix_service_sites_coords', table_name='service_sites')
    op.drop_table('service_sites')
    op.drop_index('ix_routes_technician_date', table_name='routes')
    op.drop_index('ix_routes_status', table_name='routes')
    op.drop_index('ix_routes_date', table_name='routes')
    op.drop_table('routes')
    op.drop_index('ix_technicians_name', table_name='technicians')
    op.drop_index('ix_technicians_is_active', table_name='technicians')
    op.drop_index('ix_technicians_home_coords', table_name='technicians')
    op.drop_table('technicians')
    op.drop_index('ix_opt_tasks_target_date', table_name='optimization_tasks')
    op.drop_index('ix_opt_tasks_status', table_name='optimization_tasks')
    op.drop_index('ix_opt_tasks_message_id', table_name='optimization_tasks')
    op.drop_table('optimization_tasks')
    # ### end Alembic commands ###
